import {
  Globe2,
  AppWindow,
  Braces,
  PenTool,
  Workflow,
  Cpu,
  SlidersHorizontal,
  Smartphone,
  Code2,
  Layers,
  MousePointer2,
  ShieldCheck,
  TrendingUp,
  NetworkIcon,
} from "lucide-react";

export const navigation = [
  ["home", "Home"],
  ["services", "Services"],
  ["project", "Project"],
  ["about", "About"],
  ["contact", "Contact"],
];

export const services = [
  {
    title: "Web Development",
    icon: Globe2,
    description:
      "Your digital first impression, thoughtfully built. Fast, responsive websites that work beautifully everywhere.",
    detail:
      "From a compelling company website to a content-rich platform, we create secure, accessible websites built to grow with your business.",
    features: [
      "Responsive, accessible layouts",
      "Performance and search foundations",
      "Content management integration",
    ],
  },
  {
    title: "Web Application Development",
    icon: AppWindow,
    description:
      "Powerful applications. Seamless experiences. Bring your most ambitious business ideas to the browser.",
    detail:
      "We turn your requirements into intuitive web applications with reliable architecture and a clear path from prototype to production.",
    features: [
      "Interactive dashboards and portals",
      "API and third-party integrations",
      "Authentication and user permissions",
    ],
  },
  {
    title: "Custom Software Development",
    icon: Braces,
    description:
      "Software that fits your business. Purpose-built tools to simplify work and unlock new possibilities.",
    detail:
      "Get a solution designed around your workflows. We identify opportunities to automate repetitive tasks and build tools your team enjoys using.",
    features: [
      "Workflow and process automation",
      "Tailored features and integrations",
      "Maintainable, documented code",
    ],
  },
  {
    title: "UI/UX Design",
    icon: PenTool,
    description:
      "Considered design. Effortless interaction. Digital experiences your users will love coming back to.",
    detail:
      "We combine user research, clear information architecture, and thoughtful visual design to make complex products feel simple.",
    features: [
      "User journeys and wireframes",
      "Interactive prototypes",
      "Reusable design systems",
    ],
  },
  {
    title: "System Development",
    icon: Workflow,
    description:
      "Bring everything together. Connected management systems that keep your operations moving.",
    detail:
      "From inventory and information systems to monitoring platforms, we build connected systems with useful reporting and role-based access.",
    features: [
      "Management and monitoring platforms",
      "Reporting and analytics",
      "Role-based operational workflows",
    ],
  },
  {
    title: "Networking",
    icon: NetworkIcon,
    description:
      "Reliable and secure network solutions designed to keep your systems connected and running smoothly.",
    detail:
      "We design, configure, and maintain network infrastructures that provide stable connectivity, better performance, and improved security for your organization.",
    features: [
      "LAN and Wi-Fi network setup",
      "Router and switch configuration",
      "Network troubleshooting and maintenance",
    ],
  },
];

export const projects = [
  {
    id: "Tabulation",
    title: "Pageant Tabulation System",
    subtitle:
      "A digital scoring and tabulation platform designed to simplify pageant judging and automatically calculate accurate results.",
    category: "Tabulation",
    tags: ["React", "Django", "MySQL"],
    color: "violet",
    url: "https://ptsmpc.vercel.app/",
    description:
      "A web-based pageant tabulation system that allows judges to score candidates digitally while providing administrators with an organized platform for managing candidates, criteria, judges, and final results.",
    features: [
      "Real-time candidate scoring and result calculation",
      "Candidate, judge, and scoring criteria management",
      "Automatic ranking and consolidated results",
    ],
  },

  {
    id: "Ai",
    title: "AI-Detection",
    subtitle:
      "Analyze text using advanced Artificial Intelligence models to estimate whether it was authored by AI or written by a human.",
    category: "Web Development",
    tags: ["React", "TypeScript", "Tailwind CSS"],
    image: "/projects/forma.svg",
    color: "sand",
    url: "https://ai-text-detector-frontend-black.vercel.app/",
    description:
      "An AI-powered web application designed to analyze written content and provide an estimated assessment of whether the text was generated by artificial intelligence or written by a human.",
    features: [
      "AI-powered text content analysis",
      "AI and human-written probability estimation",
      "Fast, responsive, and user-friendly interface",
    ],
  },

  {
    id: "Brgy",
    title: "System Under Development",
    subtitle: "Barangay Management System",
    category: "Mobile & Web Development System",
    tags: ["React", "Django", "PostgreSQL"],
    image: "",
    color: "blue",
    url: "",
    description:
      "A mobile and web-based Barangay Management System designed to digitize community records, resident information, document requests, announcements, and other barangay services.",
    features: [
      "Resident information and household management",
      "Barangay document and certificate request processing",
      "Announcements, records, and community service management",
    ],
  },

  {
    id: "Ecommerce",
    title: "System Under Development",
    subtitle: "E-Commerce Management System",
    category: "E-Commerce",
    tags: ["Next.js", "Laravel", "MySQL"],
    image: "",
    color: "green",
    url: "",
    description:
      "A full-stack e-commerce management system designed for managing products, customer orders, inventory, payments, and online shopping operations through a modern and responsive platform.",
    features: [
      "Product catalog and inventory management",
      "Shopping cart and order processing",
      "Customer and administrator management dashboard",
    ],
  },
];

export const technologies = [
  ["React", "⚛", "var(--accent)"],
  ["Laravel", "L", "var(--accent-soft)"],
  ["JavaScript", "JS", "var(--accent)"],
  ["TypeScript", "TS", "var(--blue-bright)"],
  ["PHP", "php", "var(--accent-soft)"],
  ["Python", "Py", "var(--accent)"],
  ["MySQL", "My", "var(--accent-soft)"],
  ["HTML", "5", "var(--blue-bright)"],
  ["CSS", "3", "var(--accent)"],
  ["Tailwind CSS", "≈", "var(--accent-soft)"],
  ["Git", "◇", "var(--blue-bright)"],
  ["GitHub", "GH", "var(--text)"],
];

export const process = [
  [
    "Discover",
    "Every great build starts with a conversation.",
    "We understand your goals, challenges, users, and requirements. Together, we define what success looks like.",
    "A shared vision & project brief",
  ],
  [
    "Plan",
    "A clear path from idea to reality.",
    "We map the features, system architecture, database, and roadmap so every decision has a purpose.",
    "Architecture & development roadmap",
  ],
  [
    "Design",
    "Thoughtful design, down to the last detail.",
    "We create clean, modern interfaces and interactive prototypes, refining the experience with your feedback.",
    "Wireframes & interactive prototype",
  ],
  [
    "Develop",
    "This is where your idea comes to life.",
    "We build with modern technologies, maintainable code, and regular checkpoints that keep you in the loop.",
    "A working, scalable application",
  ],
  [
    "Test",
    "Confidence in every click.",
    "We check functionality, responsiveness, security, and performance to prepare your application for real users.",
    "A thoroughly tested experience",
  ],
  [
    "Deploy",
    "Ready for the real world.",
    "We launch your application, document the essentials, and help you take the next step with confidence.",
    "Launch & project handover",
  ],
];

export const advantages = [
  [Cpu, "Modern Technologies", "The right tools for what comes next."],
  [
    SlidersHorizontal,
    "Customized Solutions",
    "Built around your business, from day one.",
  ],
  [Smartphone, "Responsive Design", "A great experience on every screen."],
  [
    Code2,
    "Clean & Maintainable Code",
    "A thoughtful foundation for the future.",
  ],
  [Layers, "Scalable Applications", "Room to grow with your ambitions."],
  [
    MousePointer2,
    "User-Friendly Interfaces",
    "Complexity made refreshingly simple.",
  ],
  [ShieldCheck, "Secure Development", "Careful choices at every layer."],
  [
    TrendingUp,
    "Continuous Improvement",
    "Always finding a better way forward.",
  ],
];
