
export const teamMembers = [
  {
    id: "member-01",
    name: "Charlie Pelingon, MIT",
    title: "Team Leader/Network Administrator",
    initials: "CP",
    photo: "",
    portfolioUrl: "",
    accent: "lavender",
  },
  {
    id: "member-02",
    name: "Bernie Basas, MIT",
    title: "System & Data Analyst",
    photo: "/bern.png",
    portfolioUrl: "",
    githubUrl: "",
    accent: "sage",
  },
  {
    id: "member-03",
    name: "Mike Christian C. Gealolo",
    title: "UI/UX Design/System Analyst",
    initials: "03",
    photo: "/mike.png",
    portfolioUrl: "",
    githubUrl: "",
    accent: "sky",
  },
  {
    id: "member-04",
    name: "John Kris T. Gellado",
    title: "Web Developer",
    initials: "03",
    photo: "/kris.jpg",
    portfolioUrl: "https://jkris-dev.vercel.app/",
    githubUrl: "",
    accent: "sky",
  },
  {
    id: "member-05",
    name: "Welquim B. Panogaling",
    title: "Web Developer",
    initials: "03",
    photo: "/wel.jpg",
    portfolioUrl: "https://panogaling.vercel.app/",
    githubUrl: "",
    accent: "sky",
  },
];
